config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/index'

  root 'events#index'

  get '/events', to: 'events#index'
  # get "/users/:id", to: "users#show"

  resources :attended_events

  resources :users

  resources :events
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attended_event.rb
class AttendedEvent < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :event_attended, class_name: "Event"
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: 'User'
  has_many :attended_events, foreign_key: :event_attended_id
  has_many :attendees, through: :attended_events, source: :event_attendee

  scope :past, -> { where("date < ?", Time.now) }
  scope :future, -> {where("date > ?", Time.now) }

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :attended_events, foreign_key: :event_attendee_id
  has_many :events_attended, through: :attended_events
  has_many :created_events, foreign_key: :creator_id, class_name: "Event"
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/attended_events_controller.rb
class AttendedEventsController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: :index
  def index
    @events = Event.all
  end

  def show
    @event = Event.find(params[:id])
    @creator = @event.creator
    @attendees = User.joins("INNER JOIN attended_events ON attended_events.event_attendee_id = users.id INNER JOIN events ON events.id = attended_events.event_attended_id").where('events.id' => @event)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    @event = Event.find(params[:id])
    @attendee = current_user
    @event.attendees << @attendee
    redirect_to root_path, notice: 'Thanks for signing up!'
  end

  private

  def event_params
    params.require(:event).permit(:location, :date, :creator_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @created_events = Event.where(creator_id: (params[:id]))
    @attended_events = Event.joins("INNER JOIN attended_events ON attended_events.event_attended_id = events.id INNER JOIN users ON users.id = event_attendee_id").where('users.id' => @user)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attended_events_helper.rb
module AttendedEventsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1 class="text-3xl font-bold underline">Let's find some events to attend!</h1>

<div class="block max-w-sm p-6 border border-gray-200 rounded-lg" >
  <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">Available Events</h2>
  <h3 class="mb-1 text-l font-bold">Past Events</h3>
  <ul>
    <% @events.past.each do |event| %>
      <li class="font-normal text-gray-700" >
       <%= link_to event.location, event_path(event.id) %>
      </li>
    <% end %>
  </ul> 
  <h3 class="mb-1 text-l font-bold">Future Events</h3>
  <ul>
    <% @events.future.each do |event| %>
      <li class="font-normal text-gray-700" >
       <%= link_to event.location, event_path(event.id) %>
      </li>
    <% end %>
  </ul> 
</div>

<%= button_to 'Create event', new_event_path, :method => "get", class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>

app/views/events/new.html.erb
<h1 class="max-w-sm mx-auto mb-5 mt-5 text-xl">New Event</h1>

<%= form_with model: @event, class: "max-w-sm mx-auto" do |form| %>
  <%= form.hidden_field :creator_id, value: current_user.id %>
  <div class="mb-5">
    <%= form.label :location, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.text_field :location, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="mb-5">
    <%= form.label :date, class: "block mb-2 text-sm font-medium text-gray-900" %>
    <%= form.date_field :date, class: "shadow-sm bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full p-2.5" %>
  </div>

  <div class="mb-5">
    <%= form.submit class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center"%>
  </div>
<% end %>

app/views/events/show.html.erb
<div class="block max-w-sm p-6 border border-gray-200 rounded-lg" >
  <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">
    <%= @event.location %>
  </h2>

  <div>
    <%= @event.date %>
  </div>

  <div> Creator: 
    <%= link_to @creator.email, user_path(@creator) %>
  </div>
</div>
<div>
<%= button_to 'Sign up to attend', event_path, method: 'patch', class: "text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center" %>
</div>

<div class="block max-w-sm p-6 border border-gray-200 rounded-lg" >
  <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">Attendees</h2>
  <ul>
    <% @attendees.each do |att| %>
      <li class="font-normal text-gray-700" >
       <%= att.email %>
      </li>
    <% end %>
  </ul> 
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="font-sans flex flex-col text-center sm:flex-row sm:text-left sm:justify-between py-4 px-6 bg-white shadow sm:items-baseline w-full">
      <div class="mb-2 sm:mb-0">
        <%= link_to 'Home', root_path, class: "text-2xl no-underline text-grey-darkest hover:text-blue-dark" %>
      </div>
      <div class="flex">
        <% if current_user %>
          <%= link_to 'My Events', user_path(current_user), class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
          <%= button_to 'Sign Out', destroy_user_session_path, method: 'delete', class: "text-red-700 text-lg no-underline hover:text-blue-dark ml-2" %>
        <% else %>
          <%= link_to 'Log In', new_user_session_path, class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
          <%= link_to "Sign Up", new_user_registration_path, class: "text-lg no-underline text-grey-darkest hover:text-blue-dark ml-2" %>
        <% end %>
      </div>
    </nav>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <% if current_user %>
      <div>
      Signed in as:
      <%= current_user.email %>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1 class="max-w-sm mx-auto mb-5 mt-5 text-xl" >
  <% if @user == current_user %>
    My Events
  <% else %>
    <%= @user.email %>'s Events
  <% end %>
</h1>
<div class="block max-w-sm p-6 border border-gray-200 rounded-lg" >
  <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">Events I'm hosting</h2>
  <ul>
    <% @created_events.each do |event| %>
      <li class="font-normal text-gray-700" >
       <%= link_to event.location, event_path(event.id) %>
      </li>
    <% end %>
  </ul> 
</div>
<div class="block max-w-sm p-6 border border-gray-200 rounded-lg" >
  <h2 class="mb-2 text-2xl font-bold tracking-tight text-gray-900">Events I'm attending</h2>
  <h3 class="mb-1 text-l font-bold">Past Events</h3>
  <ul>
    <% @attended_events.each do |event| %>
      <li class="font-normal text-gray-700" >
      <% if event.date < Time.now %>
       <%= link_to event.location, event_path(event.id) %>
      </li>
      <% end %>
    <% end %>
  </ul> 
  <h3 class="mb-1 text-l font-bold">Future Events</h3>
  <ul>
    <% @attended_events.each do |event| %>
      <li class="font-normal text-gray-700" >
      <% if event.date > Time.now %>
       <%= link_to event.location, event_path(event.id) %>
      </li>
      <% end %>
    <% end %>
  </ul> 
</div>